name: Run application tests with Gradle
description: Test a specified Kotlin project with Gradle

inputs:
  target_dir:
    description: Target directory where the gradle should execute tests from
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Print CI environment
      shell: bash
      run: |
        pwd
        tree .
        gradle --version

    - name: Run tests for ${{ inputs.target_dir }}
      shell: bash
      working-directory: ${{ inputs.target_dir }}
      run: gradle test --info
