spring:
  datasource:
    url: jdbc:postgresql://clients-postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: notifications_rabbit
    port: 5672
    username: admin
    password: admin
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: e63afa5e3b10f7e4652e
            clientSecret: 2786548bbeb784bea5a8c807dab7cd4d449f1c4b