spring:
  datasource:
    url: jdbc:postgresql://clients-postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: notifications-rabbit
    port: 5672
    username: admin
    password: admin

notification:
  exchange: notification_exchange
  queue: notification_queue
  routing-key: notification_routing_key
