spring:
  datasource:
    url: jdbc:postgresql://users_postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 1054728815866-b1saqkk6pvp0ekv5b6o74n4qrvoj106a.apps.googleusercontent.com
#            client-secret: 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