name: Master - Test

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - '**.kt'
      - '**.java'
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - information-service
          - reservations-service
          - users-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Run tests for ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: gradle test --info
