name: Master - Build

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - '**.kt'
      - '**.kts'
      - '**.java'
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - information-service
          - reservations-service
          - users-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.service }} with Gradle
        uses: ./.github/actions/build-app
        with:
          target_dir: ${{ matrix.service }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-artifacts
          path: ${{ matrix.service }}/build/libs/*.jar
